# Generated by Django 5.1.1 on 2025-01-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_is_approved_subscription_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='video',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='video_banners/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
    ]
